### ISSUE TITLE
De-JSX-ify most of the classes

### ISSUE THREAD

**Issue by jayands** [phenax/plasmajs#12]
The fact is that the only time we need the `.jsx` file extension is when we are actually _using_ JSX code. Rarely do the `index` files, for example, which are just exporting code from elsewhere, need to be `.jsx`. By shedding the unnecessary blanket file format, it should make Node run happier against most of the files. Without `.jsx`, we can eliminate the file extension in most references in import/export statements, so references to `'./Logger.jsx'` become `'./Logger'`. Further, we can eliminate the need for references to `index.jsx` entirely if we want everything in the folder, instead referring to the folder since Node automatically picks up `index.js` files.

**Comment by ganes1410** [comment]
hi @jayands.can i take this up?

**Comment by phenax** [comment]
@ganes1410 Sure
