### ISSUE TITLE
[Off-topic/Suggestion] A chat channel to discuss progress without creating a new issue

### ISSUE THREAD

**Issue by jayands** [phenax/plasmajs#15]
Or alternatively, codifying ideas _into_ issues. The usual suspects nowadays are [IRC], [Discord], and [Slack], but some people still use [Skype] too. Personally, I have a hard vote *against* Skype, though, because there are no definitive URLs which can get you back to the group chat quickly if you close it, and MS doesn't really treat it like a first-class product.

[Skype]:http://enwp.org/Skype
[IRC]:http://enwp.org/Internet_Relay_Chat
[Discord]:http://enwp.org/Discord_(software)
[Slack]:http://enwp.org/Slack_(software)

Now, not everyone has a copy of Discord or Slack. On the other hand, IRC can be confusing for beginners: "How do I connect to \#plasmajs on Freenode? What even _is_ Freenode? What's this `+ix` I see by my nickname?" etc.

Thoughts?

**Comment by phenax** [comment]
Discord sounds good. The web client is pretty easy to use.

**Comment by jayands** [comment]
[Done](https://discord.gg/b9Z4b6r)
Someone should update the README to include it: https://discord.gg/b9Z4b6r
@ganes1410 Join the discord server, please

@mperitz I don't know if you're still interested in this project, but we now have a Discord server
