### ISSUE TITLE
Upgrade vulnerable packages

### ISSUE THREAD

**Issue by phenax** [phenax/plasmajs#19]
Running `npm audit` shows that some of the packages are at versions known to be vulnerable.

**Comment by yaoandy107** [comment]
I have give it a try. Found 32 vulnerabilities with `npm audit`, but it can only be auto fix in 24 vulnerabilities without force,  may I use force to fix it, or just left it alone? I have use `npm run test` to check if it is still working after using force, but I am not sure if there is some other problem when using force.

**Comment by phenax** [comment]
@yaoandy107, Give it a go. You can run the test to verify if there are any breaking changes for us. If something does break then we can for now fix the auto fix ones and then fix the broken changes later.

**Comment by yaoandy107** [comment]
I have sent a PR recently. #20
