### ISSUE TITLE
Lacks proper documentation

### ISSUE THREAD

**Issue by phenax** [phenax/plasmajs#3]
Need to document the features and usage in detail. Either as a gh-page branch or a Wiki entry on github.

**Comment by sourabhpruthi10** [comment]
Hello i want to work on this issue.Please tell me what i need to do and what is expected from me

**Comment by phenax** [comment]
@sourabh1031 
What we need for this project is good documentation of features. So as a first step towards that goal, we can copy some of the stuff in the README.md to Github's wiki section.(https://guides.github.com/features/wikis/)

**Comment by william13murphy** [comment]
@phenax Hi, I am a first time contributor and believe this issue would be a great start. Can you verify if this issue still needs addressed. If so, I would love to help out!

**Comment by phenax** [comment]
@william13murphy, yes! This project really needs a decent documentation.
If you're interested, would love your help in one of my other projects too - https://github.com/phenax/pipey.

**Comment by william13murphy** [comment]
@phenax As a start, I have added the README's content to my own repo (plasmajs-wiki). Please review my changes at the following link, [https://github.com/william13murphy/plasmajs-wiki](https://github.com/william13murphy/plasmajs-wiki).

If you have any recommendations or preferred content for the new wiki page, please let me know and I will make the changes accordingly.

**Comment by phenax** [comment]
@william13murphy, Looks great! I think the next step would be splitting into pages. For now, "Getting started", "Middlewares", "Routing" should suffice.

**Comment by ghost** [comment]
Can I help too? Is my first contribution and I think would be a good start.

**Comment by phenax** [comment]
@ManuelPortero, feel free. Let me know if you need any help in getting started. :)

**Comment by ghost** [comment]
I already read all the tasks and the wiki; in the next week I gonna proceed to split that in pages as you recommend. Thanks for the opportunity.
Regards.
Manuel Portero.

**Comment by ghost** [comment]
Hi! I could split the main document in three pages but I need acces to the wiki for post the content and give it format. Is my first contribution. If i'm forgetting or missing something I would apreciatte a comment about it.

[gettingStarted.txt](https://github.com/phenax/plasmajs/files/4869243/gettingStarted.txt)
[middlewares.txt](https://github.com/phenax/plasmajs/files/4869244/middlewares.txt)
[routes.txt](https://github.com/phenax/plasmajs/files/4869245/routes.txt)

**Comment by phenax** [comment]
I think that it'll be better version-control wise to have it in a seperate folder called `/docs` and link it in the README.md.

Can you create a PR with this contents as markdown in a `/docs` folder?

**Comment by ghost** [comment]
Yes.I'll present something for the next week.  
Regards.
Manuel Portero.

**Comment by ghost** [comment]
PR done and README.md updated. If there is something to say about that please comment.
Regards.
Manuel Portero.

**Comment by phenax** [comment]
@ManuelPortero, I can't find the pull request. Let me know if you need any help with it.

**Comment by ManuelPortero** [comment]
[](url)
![Captura de pantalla de 2020-07-08 09-09-51](https://user-images.githubusercontent.com/43322688/86894380-e4ba6800-c0fa-11ea-9319-ec7baaba6677.png)

**Comment by phenax** [comment]
I've merged the PR. Thank you for the contribution!! :smile:

**Comment by ghost** [comment]
You welcome, It's been nice work in a collective project for first time :)

**Comment by phenax** [comment]
@ManuelPortero You should keep at it! Visit https://www.firsttimersonly.com/ and https://up-for-grabs.net if you haven't already. Enjoy the open source world. :)
